### ISSUE TITLE
Javascript SDK library is not detecting WebSerial on Chrome

### ISSUE THREAD

**Issue by jnthas** [improv-wifi/sdk-serial-js#121]
Javascript SDK library is warning that my browser does not support WebSerial but I'm using
```
Google Chrome
Version 108.0.5359.124 (Oficial version) 64 bits on Ubuntu 22.04
```

The same is happening with BLE Javascript SDK.

Evidence using `<improv-wifi-serial-launch-button>`:
https://jnthas.github.io/improv-wifi/index-improv.html

When I use `<esp-web-install-button>` it works fine:
https://jnthas.github.io/improv-wifi/index.html

**Comment by balloob** [comment]
We test it like this:

https://github.com/improv-wifi/sdk-serial-js/blob/main/src/serial-launch-button.ts#L4-L6

The reason your code doesn't work is because the tag is `<improf-wifi-launch-button>` for the BLE SDK. And you have the word `serial` in there.

If you're using the JavaScript SDK, you do need to add serial in it.

**Comment by balloob** [comment]
Use this as your JS import

```html
<script type="module" src="https://unpkg.com/improv-wifi-serial-sdk@2.5.0/dist/web/serial-launch-button.js?module"></script>

**Comment by jnthas** [comment]
I got it. The import is different for BLE and Serial. It was not clear to me reading https://www.improv-wifi.com/code/ or the repo of Serial SDK.
Thanks for the clarification.
